### ISSUE TITLE
rules

### ISSUE THREAD

**Issue by ikexing-cn** [bingling-sama/BakaHDT#1]
# 群规
`1. 不允许多次加群退群,超过【3次】会被本群拉入黑名单！`
`2. 禁止以任何形式键政/脏话/商业广告/非私人服务器类消息的发布`
`3. 禁止以任何形式发布R18等【限制级】内容,擦边球也不行`
`4. 禁止以任何形式发布付费资源`

## 不知道要不要的规则 (你看着来)
`1.如果不看jei来本群问魔改后的合成表的，一律禁言5分钟，3次飞机票`
`2.魔改问题先看wiki，魔改问题先看wiki，魔改问题先看wiki，重要的事情说三遍，如果不看就来问，一律禁言10分钟，3次飞机票`
`3.如果要问问题，请一律附上截图，无截图一次3分钟`
`4.群内大佬不是万能的，也不是神，如果解决不了问题可能是去翻wiki，请不要随意at，违者5分钟，3次飞机票`

**Comment by bingling-sama** [comment]
## 黑名单功能 *Waiting for OP permission...*
- [ ] 入群申请自动拒绝黑名单成员申请
- [ ] 管理员专用 &ban &unban 指令，添加/移除黑名单

**Comment by ikexing-cn** [comment]
## 提问：需求追加

一个命令后发送下面这段话（或许你需要酌情自改xD）：
魔改时请附上`crafttweaker.log`和你认为只要是**有可能会出错的代码**发送到pastebin链接。

**Comment by bingling-sama** [comment]
> ## 提问：需求追加
> 一个命令后发送下面这段话（或许你需要酌情自改xD）：
> 魔改时请附上`crafttweaker.log`和你认为只要是**有可能会出错的代码**发送到pastebin链接。

可以另发一个issues吗

**Comment by bingling-sama** [comment]
此需求已完成（&rules）
