### ISSUE TITLE
崩溃报告命令

### ISSUE THREAD

**Issue by vfyjxf** [bingling-sama/BakaHDT#4]
添加一个命令，输出如何发崩溃报告，附带一些如何看崩溃报告的教程（还可以来张让我943教你发崩溃报告的图 bushi）

**Comment by bingling-sama** [comment]
finished #[https://github.com/bingling-sama/BakaHDT/commit/d06bd8cf02c6b5bae26aa39a288ca6e98a8a2e4f](url)
